// Copyright (c) 2023-2024, The BitcoinMW Developers
// Some code and concepts from:
// * Grin: https://github.com/mimblewimble/grin
// * Arti: https://gitlab.torproject.org/tpo/core/arti
// * BitcoinMW: https://github.com/bitcoinmw/bitcoinmw
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// Build a configuration based on the specified input parameters. Checks for duplicates and
/// returns and error if any are specified.
/// # Input Parameters
/// * `$configurable` - The name of the [`crate::Configurable`] struct to configure.
/// * `$enum_name` - The name of the enum that coresponds to this struct.
/// * `$vec` - A vector of variants from the $enum_name to configure this instance with.
/// # Return
/// An instance of the [`crate::Configurable`] struct with the specified values. Anything not
/// specified will take on the default value.
/// # Errors
/// [`bmw_err::ErrKind::Configuration`] - if a duplicate value is specified.
/// # Also see
/// [`crate::Configurable`]
/// # Examples
///```
/// use bmw_err::*;
/// use bmw_derive::*;
/// use std::collections::HashSet;
///
/// // build a struct, normally the Configurable trait would be derived via proc macro
/// // usize, bool, u8, u16, u32, u64, u128, String and (String, String) are supported types
/// // Vec of any of those types are also supported
/// struct MyStruct {
///     threads: usize,
///     timeout: usize,
/// }
///
/// // implement the Default trait
/// impl Default for MyStruct {
///     fn default() -> Self {
///         Self {
///             threads: 1,
///             timeout: 0,
///         }
///     }
/// }
///
/// // auto generated by macro
/// enum MyStruct_Options {
///     Threads(usize),
///     Timeout(usize),
/// }
///
/// // auto generated by macro
/// impl MyStruct {
///     fn new() -> Self {
///         Self::default()
///     }
///     fn required() -> Vec<String> { vec![] }
/// }
///
/// // auto generated by macro
/// impl Configurable for MyStruct {
///     fn set_usize(&mut self, name: &str, value: usize) {
///         if name == "Threads" {
///             self.threads = value;
///         }
///         if name == "Timeout" {
///             self.timeout = value;
///         }
///     }
///
///     fn set_bool(&mut self, name: &str, value: bool) {}
///     fn set_u8(&mut self, name: &str, value: u8) {}
///     fn set_u16(&mut self, name: &str, value: u16) {}
///     fn set_u32(&mut self, name: &str, value: u32) {}
///     fn set_u64(&mut self, name: &str, value: u64) {}
///     fn set_u128(&mut self, name: &str, value: u128) {}
///     fn set_string(&mut self, name: &str, value: String) {}
///     fn set_string_tuple(&mut self, name: &str, value: (String, String)) {}
///     fn allow_dupes(&self) -> HashSet<String> { HashSet::new() }
/// }
///
/// // auto generated by macro
/// impl MyStruct_Options {
///     fn name(&self) -> &str {
///         match self {
///              MyStruct_Options::Threads(v) => "Threads",
///              MyStruct_Options::Timeout(v) => "Timeout"
///         }
///     }
///     fn value_usize(&self) -> Option<usize> {
///         match self {
///             MyStruct_Options::Threads(v) => Some(*v),
///             MyStruct_Options::Timeout(v) => Some(*v),
///             _ => None,
///         }
///     }
///     fn value_bool(&self) -> Option<bool> { None }
///     fn value_u8(&self) -> Option<u8> { None }
///     fn value_u16(&self) -> Option<u16> { None }
///     fn value_u32(&self) -> Option<u32> { None }
///     fn value_u64(&self) -> Option<u64> { None }
///     fn value_u128(&self) -> Option<u128> { None }
///     fn value_string(&self) -> Option<String> { None }
///     fn value_string_tuple(&self) -> Option<(String, String)> {
///         None
///     }
/// }
///
/// fn main() -> Result<(), Error> {
///     // call config with the specifed values. The values are changed from snake case
///     // to `Pascal` format.
///     let x = config!(MyStruct, MyStruct_Options, vec![Threads(4), Timeout(100)])?;
///
///     // if a value is not specified, the default is used. In this case both values
///     // were set in the macro call.
///     assert_eq!(x.threads, 4);
///     assert_eq!(x.timeout, 100);
///
///     let x = config!(MyStruct, MyStruct_Options, vec![Threads(10)])?;
///
///     assert_eq!(x.threads, 10);
///     assert_eq!(x.timeout, 0);
///
///     // Threads is specified twice so it's an error
///     assert!(config!(MyStruct, MyStruct_Options, vec![Threads(10), Threads(20)]).is_err());
///
///     Ok(())
/// }
///```
#[macro_export]
macro_rules! config {
	( $configurable:ident, $enum_name:ident, $vec:expr ) => {{
		use bmw_derive::Configurable;
		use bmw_err::*;
		use std::collections::HashSet;
		use $enum_name::*;

		let mut ret = $configurable::new();

		let mut name_set: HashSet<String> = HashSet::new();
		let mut err = None;
		let options: Vec<$enum_name> = $vec;

		for cfg in options {
			let name = cfg.name();
			if name_set.contains(name.clone()) && !ret.allow_dupes().contains(name.clone()) {
				let text = format!("config option ({}) was specified more than once", name);
				err = Some(Err(err!(ErrKind::Configuration, text)));
			}
			name_set.insert(name.to_string());
			match cfg.value_u8() {
				Some(value) => ret.set_u8(name, value),
				None => {}
			}
			match cfg.value_u16() {
				Some(value) => ret.set_u16(name, value),
				None => {}
			}
			match cfg.value_u32() {
				Some(value) => ret.set_u32(name, value),
				None => {}
			}
			match cfg.value_u64() {
				Some(value) => ret.set_u64(name, value),
				None => {}
			}
			match cfg.value_u128() {
				Some(value) => ret.set_u128(name, value),
				None => {}
			}
			match cfg.value_usize() {
				Some(value) => ret.set_usize(name, value),
				None => {}
			}
			match cfg.value_string() {
				Some(value) => ret.set_string(name, value),
				None => {}
			}
			match cfg.value_bool() {
				Some(value) => ret.set_bool(name, value),
				None => {}
			}
			match cfg.value_string_tuple() {
				Some(value) => ret.set_string_tuple(name, value),
				None => {}
			}
		}

		for r in $configurable::required() {
			if !name_set.contains(&r) {
				let text = format!("required option ({}) was not specified", r);
				err = Some(Err(err!(ErrKind::Configuration, text)));
			}
		}

		match err {
			Some(e) => e,
			None => Ok(ret),
		}
	}};
}
