[package]
name = "bmw"
version = "0.0.3-beta.2"
authors = ["The BitcoinMW Developers"]
description = "Bitcoin Mimblewimble (BMW) core libraries"
license = "Apache-2.0"
repository = "https://github.com/cgilliard/bitcoinmw"
keywords = [ "crypto", "bitcoinmw"]
readme = "README.md"
exclude = ["**/*.bmw", "**/*.bmw"]
build = "src/build/build.rs"
edition = "2021"

[workspace]
members = [
	"error",
	"deps",
	"log",
	"test",
	"util",
	"derive",
	"ser",
	"config",
	"evh"
]
exclude = ["etc"]

[dependencies]

bmw_deps    = { path = "./deps"        }
bmw_conf    = { path = "./config"      }
bmw_err     = { path = "./error"       }
bmw_log     = { path = "./log"         }
bmw_util    = { path = "./util"        }
bmw_derive  = { path = "./derive"      }
bmw_ser     = { path = "./ser"         }
bmw_evh     = { path = "./evh"         }

[dev-dependencies]
bmw_test    = { path = "./test"        }

[target.'cfg(not(target_os = "windows"))'.dependencies]
jemallocator = "0.5.4"

[build-dependencies]
built = { version = "0.7.1", features = ["git2"]}

