[package]
name = "bmw_deps"
version = "0.0.3-beta.1"
authors = ["The BitcoinMW Developers"]
description = "Dependencies of this library"
license = "Apache-2.0"
repository = "https://github.com/cgilliard/bitcoinmw"
keywords = [ "crypto", "bitcoinmw"]
readme = "README.md"
exclude = ["**/*.bmw", "**/*.bmw"]
edition = "2021"

[dependencies]
futures = "0.3.23"
failure = "0.1.0"
failure_derive = "0.1.0"
dirs = "5.0.1"
substring = "1.4.5"
path-clean = "0.1.0"
colored = "2.0.0"
rand = "0.8.4"
lazy_static = "1.4.0"
backtrace = "0.3.63"
chrono = "0.4"
dyn-clone = "1.0.9"
random-string = "1.0.0"
libc = "0.2.132"
errno = "0.2.8"
portpicker = "0.1.1"
winapi = { version = "0.3.9", features = ["winsock2"] }
nix = { version = "0.26.4", features = ["socket", "net"] }
bitvec = "1.0.1"
rustls = "0.20.9"
rustls-pemfile = "1.0.3"
webpki-roots = "0.25.2"
webpki = "0.22.4"
libmath = "0.2.1"
sha-1 = "0.10.0"
base64 = "0.13.0"
byteorder = "1.4.2"
rand_core = "0.6.4"
flate2 = "1.0.28"
num-format = "0.4.4"
itertools = "0.12.1"
downcast = "0.11.0"
url = "2.5.0"

[target.'cfg(target_os = "macos")'.dependencies]
kqueue-sys = "1.0.2"

[target.'cfg(target_os = "windows")'.dependencies]
wepoll-sys = "3.0.1"
