[package]
name = "bmw_deps"
version = "0.0.3-beta.2"
authors = ["The BitcoinMW Developers"]
description = "Dependencies used by BMW"
license = "Apache-2.0"
repository = "https://github.com/cgilliard/bitcoinmw"
keywords = [ "crypto", "bitcoinmw"]
readme = "README.md"
exclude = ["**/*.bmw", "**/*.bmw"]
edition = "2021"

[dependencies]
futures = "0.3.30"
failure = "0.1.8"
failure_derive = "0.1.8"
dirs = "5.0.1"
substring = "1.4.5"
ring = "0.17.8"
path-clean = "1.0.1"
colored = "2.1.0"
rand = "0.8.5"
lazy_static = "1.4.0"
backtrace = "0.3.69"
chrono = "0.4.35"
dyn-clone = "1.0.17"
random-string = "1.1.0"
portpicker = "0.1.1"
bitvec = "1.0.1"
libmath = "0.2.1"
sha-1 = "0.10.1"
base64 = "0.22.0"
byteorder = "1.5.0"
rand_core = "0.6.4"
flate2 = "1.0.28"
num-format = "0.4.4"
itertools = "0.12.1"
downcast = "0.11.0"
url = "2.5.0"
errno = "0.3.8"
url_path = "0.1.3"


[target.'cfg(target_os = "macos")'.dependencies]
kqueue-sys = "1.0.4"
nix = { version = "0.28.0", features = ["socket", "net"] }
libc = "0.2.153"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.52.0", features = ["Win32_Networking_WinSock"] }
wepoll-sys = "3.0.1"

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.28.0", features = ["socket", "net", "event", "poll"] }
libc = "0.2.153"
