[package]
name = "bmw_deps"
version = "0.0.3-beta.2"
authors = ["The BitcoinMW Developers"]
description = "Dependencies used by BitcoinMW"
license = "Apache-2.0"
repository = "https://github.com/cgilliard/bitcoinmw"
keywords = [ "crypto", "bitcoinmw"]
readme = "README.md"
exclude = ["**/*.bmw", "**/*.bmw"]
edition = "2021"

[dependencies]
dyn-clone = { path = "../crates/dyn-clone-1.0.17" }
downcast = { path = "../crates/downcast-0.11.0" }

[target.'cfg(target_os = "macos")'.dependencies]

[target.'cfg(target_os = "windows")'.dependencies]

[target.'cfg(target_os = "linux")'.dependencies]
